spring:
  application:
    name: mybatisplus
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/mp0614
    username: root
    password: ${MYSQL_PASSWORD:default_value}
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: boolDel
      logic-delete-value: 1
      logic-not-delete-value: 0